import { ClauseAnalysis, InputDocument } from '@/types';

export const mockDocuments: InputDocument[] = [
  {
    id: '1',
    document_name: 'MURABAHA_CONTRACT_Q1_2026.pdf',
    document_type: 'Murabaha',
    timestamp: '2026-02-12T10:30:00Z',
    analysis_status: 'complete',
    total_clauses: 42,
    analyzed_clauses: 42,
    uploaded_by: 'user-1',
    page_count: 28,
    language: 'English',
    critical_clauses: 2,
  },
  {
    id: '2',
    document_name: 'IJARAH_LEASE_DRAFT.docx',
    document_type: 'Ijarah',
    timestamp: '2026-02-10T14:15:00Z',
    analysis_status: 'complete',
    total_clauses: 35,
    analyzed_clauses: 35,
    uploaded_by: 'user-1',
    page_count: 22,
    language: 'English',
    critical_clauses: 1,
  },
  {
    id: '3',
    document_name: 'SUKUK_ISSUANCE_2026.pdf',
    document_type: 'Sukuk',
    timestamp: '2026-02-08T09:00:00Z',
    analysis_status: 'complete',
    total_clauses: 56,
    analyzed_clauses: 56,
    uploaded_by: 'user-1',
    page_count: 34,
    language: 'English',
    critical_clauses: 4,
  },
  {
    id: '4',
    document_name: 'MUSHARAKAH_PARTNERSHIP.pdf',
    document_type: 'Musharakah',
    timestamp: '2026-02-06T16:45:00Z',
    analysis_status: 'complete',
    total_clauses: 28,
    analyzed_clauses: 28,
    uploaded_by: 'user-1',
    page_count: 18,
    language: 'English',
    critical_clauses: 0,
  },
  {
    id: '5',
    document_name: 'TAWARRUQ_FINANCING.docx',
    document_type: 'Tawarruq',
    timestamp: '2026-02-04T11:20:00Z',
    analysis_status: 'complete',
    total_clauses: 31,
    analyzed_clauses: 31,
    uploaded_by: 'user-1',
    page_count: 20,
    language: 'English/Arabic',
    critical_clauses: 3,
  },
];

export const mockClauses: ClauseAnalysis[] = [
  {
    id: 'c1',
    document_id: '1',
    clause_number: '1.1',
    clause_text: 'The Seller agrees to sell and the Buyer agrees to purchase the Subject Matter described in Schedule A at the Murabaha Sale Price, which includes the Cost Price plus the agreed Profit Margin as detailed in Clause 3.2.',
    classification: 'Sale Agreement',
    severity: 'low',
    confidence_score: 0.95,
    shariah_issues: [],
    sama_issues: [],
    findings: 'Clause meets all regulatory requirements. The sale agreement structure follows AAOIFI FAS 28 Murabaha standard. Cost-plus structure is clearly defined with transparent profit margin disclosure.',
    remediation: 'No action required.',
    subclauses: [],
    is_critical_for_shariah: false,
    contains_arabic: false,
    verdict: 'compliant',
    created_at: '2026-02-12T10:35:00Z',
  },
  {
    id: 'c2',
    document_id: '1',
    clause_number: '2.1',
    clause_text: 'The Buyer shall pay the total Murabaha Sale Price in 36 equal monthly instalments commencing on the first Business Day following the Delivery Date. Late payment shall incur a penalty charge of 2% per annum on the outstanding amount.',
    classification: 'Payment Terms',
    severity: 'medium',
    confidence_score: 0.82,
    shariah_issues: ['Late payment penalty of 2% per annum may constitute Riba (interest) if retained as income by the Seller. AAOIFI SS 8 requires that late payment penalties be donated to charity, not retained as profit.'],
    sama_issues: ['SAMA circular CS/IMEF/2019/1 requires clear disclosure of penalty mechanisms and their Shariah treatment in consumer-facing documentation.'],
    findings: 'The late payment penalty clause raises potential Shariah concerns. While payment schedules are permissible, the penalty structure must comply with AAOIFI guidelines requiring charitable donation of penalty amounts.',
    remediation: 'Add explicit language stating that any late payment charges collected shall be donated to a charitable fund and not retained as income by the institution. Reference AAOIFI SS 8 paragraph 5/3.',
    subclauses: ['2.1.a: Payment shall be made via bank transfer to the designated account.', '2.1.b: Early settlement is permitted with mutual agreement.'],
    is_critical_for_shariah: false,
    contains_arabic: false,
    verdict: 'needs_review',
    created_at: '2026-02-12T10:36:00Z',
  },
  {
    id: 'c3',
    document_id: '1',
    clause_number: '3.1',
    clause_text: 'In the event of default by the Buyer, the Seller reserves the right to charge compound interest on the outstanding balance at a rate of SIBOR plus 3% per annum, calculated daily and capitalised monthly.',
    classification: 'Default & Remedies',
    severity: 'critical',
    confidence_score: 0.98,
    shariah_issues: ['Compound interest (Riba al-Fadl) is explicitly prohibited under AAOIFI Shariah Standards. This clause directly violates AAOIFI SS 8 and the fundamental prohibition of Riba in Islamic finance.', 'Reference to SIBOR benchmark rate for penalty calculation creates additional Riba concerns.'],
    sama_issues: ['SAMA requires all Islamic finance products to be free from Riba-based mechanisms. This clause would fail SAMA compliance review.'],
    findings: 'CRITICAL VIOLATION: This clause contains explicit compound interest provisions which are fundamentally incompatible with Shariah principles. The use of SIBOR-linked interest compounding constitutes Riba al-Fadl.',
    remediation: 'Remove all references to compound interest and SIBOR-linked calculations. Replace with a Shariah-compliant default mechanism such as: (1) Fixed penalty amount donated to charity per AAOIFI SS 8, or (2) Acceleration of remaining instalments, or (3) Right to repossess the Subject Matter.',
    subclauses: [],
    is_critical_for_shariah: true,
    contains_arabic: false,
    verdict: 'non_compliant',
    created_at: '2026-02-12T10:37:00Z',
  },
  {
    id: 'c4',
    document_id: '1',
    clause_number: '4.1',
    clause_text: 'The Subject Matter shall be delivered to the Buyer at the address specified in Schedule B within 30 Business Days from the date of this Agreement. Risk and ownership shall transfer to the Buyer upon delivery and acceptance.',
    classification: 'Delivery & Risk Transfer',
    severity: 'low',
    confidence_score: 0.93,
    shariah_issues: [],
    sama_issues: [],
    findings: 'Delivery and risk transfer provisions comply with AAOIFI FAS 28. The requirement for the Seller to bear risk until delivery aligns with Shariah principles of ownership liability.',
    remediation: 'No action required.',
    subclauses: [],
    is_critical_for_shariah: false,
    contains_arabic: false,
    verdict: 'compliant',
    created_at: '2026-02-12T10:38:00Z',
  },
  {
    id: 'c5',
    document_id: '1',
    clause_number: '5.1',
    clause_text: 'The Buyer acknowledges that the Profit Margin of 4.5% per annum applied to the Cost Price has been mutually agreed upon and is fixed for the duration of this Agreement. The Seller warrants that the Cost Price represents the actual acquisition cost.',
    classification: 'Profit Rate',
    severity: 'low',
    confidence_score: 0.91,
    shariah_issues: [],
    sama_issues: [],
    findings: 'The fixed profit margin structure is compliant with Murabaha principles. Transparency in cost price and profit disclosure meets AAOIFI requirements.',
    remediation: 'No action required.',
    subclauses: [],
    is_critical_for_shariah: false,
    contains_arabic: false,
    verdict: 'compliant',
    created_at: '2026-02-12T10:39:00Z',
  },
  {
    id: 'c6',
    document_id: '1',
    clause_number: '6.1',
    clause_text: 'يحق للبائع أن يبيع حصته من الأرباح لطرف ثالث دون موافقة المشتري المسبقة.',
    classification: 'Profit Rights Transfer',
    severity: 'high',
    confidence_score: 0.78,
    shariah_issues: ['Transfer of profit rights to a third party without buyer consent may violate the principle of mutual agreement (Taradi) required in Islamic contracts.'],
    sama_issues: ['SAMA consumer protection guidelines require explicit consent for assignment of contractual rights.'],
    findings: 'This Arabic clause permits unilateral transfer of profit rights which may not align with Islamic contractual principles requiring mutual consent.',
    remediation: 'Amend to require written consent from both parties before any transfer of profit rights to a third party.',
    subclauses: [],
    is_critical_for_shariah: true,
    contains_arabic: true,
    verdict: 'needs_review',
    created_at: '2026-02-12T10:40:00Z',
  },
];

export const dashboardStats = {
  analysesThisMonth: 12,
  monthlyLimit: 50,
  totalCompliant: 284,
  compliantTrend: 18,
  totalNeedsReview: 47,
  reviewTrend: -5,
  totalNonCompliant: 11,
  nonCompliantTrend: 3,
};
