import { Page, View, Text, Image, StyleSheet } from '@react-pdf/renderer';
import { C, F, SIZE } from '../tokens';
// Use logo from public folder (accessible at runtime)
const fortivLogoWhite = '/fortiv-logo.jpg';
import type { ReportSummary } from '@/types/pdf.types';

const s = StyleSheet.create({
    page: { backgroundColor: C.white, fontFamily: F.normal },

    // ── Header ──
    header: {
        backgroundColor: C.navy,
        height: SIZE.headerH,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: SIZE.pageMargin,
    },
    logo: { width: SIZE.logoW },
    headerRight: { alignItems: 'flex-end' },
    headerTitle: { color: C.white, fontSize: 11, fontFamily: F.bold },
    headerSub: { color: C.white, fontSize: 8, opacity: 0.7, marginTop: 2 },

    // ── Body ──
    body: { paddingHorizontal: SIZE.pageMargin, paddingVertical: 24 },

    sectionLabel: {
        fontSize: 8, fontFamily: F.bold, color: C.gray500,
        letterSpacing: 1, textTransform: 'uppercase',
        marginBottom: 6, marginTop: 20,
    },

    // ── Table ──
    metaTable: { borderWidth: 1, borderColor: C.tableBorder, borderRadius: SIZE.radius },
    metaRow: {
        flexDirection: 'row', borderTopWidth: 1, borderTopColor: C.tableBorder,
    },
    metaFirstRow: { borderTopWidth: 0 },
    metaKey: {
        width: 120, padding: SIZE.cellPad, backgroundColor: C.tableAlt,
        borderRightWidth: 1, borderRightColor: C.tableBorder,
        fontSize: 8, fontFamily: F.bold, color: C.gray500,
    },
    metaVal: { flex: 1, padding: SIZE.cellPad, fontSize: 9, color: C.gray700, lineHeight: 1.4 },

    // ── Footer ──
    footer: {
        position: 'absolute',
        bottom: 18,
        left: SIZE.pageMargin,
        right: SIZE.pageMargin,
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderTopWidth: 1,
        borderTopColor: C.gray200,
        paddingTop: 5,
    },
    footerText: { fontSize: 8, color: C.gray400 },
});

interface Props {
    summary: ReportSummary;
}

export function FooterDisclaimer({ summary }: Props) {
    return (
        <Page size="A4" style={s.page}>
            {/* ── Header ── */}
            <View fixed style={s.header}>
                <Image src={fortivLogoWhite} style={s.logo} />
                <View style={s.headerRight}>
                    <Text style={s.headerTitle}>Shariah Compliance Report</Text>
                    <Text style={s.headerSub}>Disclaimer & Signature</Text>
                </View>
            </View>

            <View style={s.body}>
                {/* ── Disclaimer ── */}
                <Text style={s.sectionLabel}>Disclaimer</Text>
                <View style={s.metaTable}>
                    <View style={[s.metaRow, s.metaFirstRow]}>
                        <Text style={s.metaKey}>Legal Notice</Text>
                        <Text style={s.metaVal}>
                            This report is generated by the Fortiv AI Shariah Compliance Screener for
                            internal review only. It does not constitute a Shariah fatwa or legal opinion.
                            All findings must be reviewed by a qualified Shariah scholar before execution.
                        </Text>
                    </View>
                    <View style={s.metaRow}>
                        <Text style={s.metaKey}>Frameworks</Text>
                        <Text style={s.metaVal}>
                            AAOIFI Shariah Standards (current edition) · SAMA Islamic Finance Regulations
                            · Approved Internal Contract Templates
                        </Text>
                    </View>
                    <View style={s.metaRow}>
                        <Text style={s.metaKey}>Liability</Text>
                        <Text style={s.metaVal}>
                            Fortiv Solutions accepts no liability for decisions made solely on the basis
                            of this automated report.
                        </Text>
                    </View>
                </View>

                {/* ── Signature ── */}
                <Text style={[s.sectionLabel, { marginTop: 20 }]}>Signature</Text>
                <View style={s.metaTable}>
                    <View style={[s.metaRow, s.metaFirstRow]}>
                        <Text style={s.metaKey}>Analyst</Text>
                        <Text style={s.metaVal}>{summary.analystName}</Text>
                    </View>
                    <View style={s.metaRow}>
                        <Text style={s.metaKey}>Email</Text>
                        <Text style={s.metaVal}>{summary.analystEmail}</Text>
                    </View>
                    <View style={s.metaRow}>
                        <Text style={s.metaKey}>Date</Text>
                        <Text style={s.metaVal}>{summary.generatedAt}</Text>
                    </View>
                    <View style={s.metaRow}>
                        <Text style={s.metaKey}>Platform</Text>
                        <Text style={s.metaVal}>Fortiv Solutions · AI Shariah Screener v1.0</Text>
                    </View>
                </View>
            </View>

            {/* ── Footer ── */}
            <View fixed style={s.footer}>
                <Text style={s.footerText}>
                    Fortiv Solutions  ·  AI Shariah Compliance Screener  ·  Confidential
                </Text>
                <Text
                    style={s.footerText}
                    render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
                />
            </View>
        </Page>
    );
}
